[project]
name = "semantic-kernel-workshop"
version = "0.1.0"
description = "A workshop for Semantic Kernel"
readme = "README.md"
dependencies = [
    "a2a-sdk>=0.2.8",
    "fastapi>=0.116.0",
    "httpx>=0.28.1",
    "python-dotenv==1.0.1",
    "requests>=2.32.3",
    "semantic-kernel==1.31.0",
    "uvicorn>=0.35.0",
]